apiVersion: v2
name: log10x-filebeat
description: A Helm chart for Kubernetes for Log10x + Filebeat
keywords:
  - log10x
  - logging
  - elastic
  - filebeat
# type: application
version: 0.3.0
appVersion: 0.11.8
icon: https://helm.elastic.co/icons/beats.png
home: https://github.com/log-10x/elastic-helm-charts
sources:
  - https://github.com/elastic/beats
maintainers:
  - name: dor-levi
    email: dor.levi@l1x.co
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Added Log10x integration to filebeat"
