{{- if and .Values.tenx.enabled .Values.tenx.licenseJwt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logstash.fullname" . }}-tenx-license
  labels:
    app: {{ template "logstash.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  license-jwt: {{ .Values.tenx.licenseJwt | b64enc | quote }}
{{- end }}
{{- if and .Values.tenx.enabled .Values.tenx.gitToken }}
{{- if .Values.tenx.licenseJwt }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logstash.fullname" . }}-tenx-git-token
  labels:
    app: {{ template "logstash.fullname" . }}
    chart: {{ .Chart.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  token: {{ .Values.tenx.gitToken | b64enc | quote }}
{{- end }}
