{{- $licenseJwt := include "tenx.licenseJwt" . }}
{{- $renderLicense := and .Values.tenx.enabled $licenseJwt }}
{{- if $renderLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "filebeat.fullname" . }}-tenx-license
  labels:
    app: {{ template "filebeat.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{ .Values.tenx.licenseSecretKey | default "license-jwt" }}: {{ $licenseJwt | b64enc | quote }}
{{- end }}
{{- if and .Values.tenx.enabled .Values.tenx.gitToken }}
{{- if $renderLicense }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "filebeat.fullname" . }}-tenx-git-token
  labels:
    app: {{ template "filebeat.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  token: {{ .Values.tenx.gitToken | b64enc | quote }}
{{- end }}
